const screenCatalog = [
  { tabId: 'tab-dashboard', label: 'لوحة التحكم', aliases: ['لوحه التحكم', 'لوحه', 'الرئيسيه', 'الداشبورد', 'dashboard'] },
  { tabId: 'tab-accounts', label: 'الحسابات', aliases: ['الحسابات', 'دليل الحسابات', 'شجره الحسابات', 'accounts'] },
  { tabId: 'tab-customers', label: 'العملاء', aliases: ['العملاء', 'العملا', 'الزبائن', 'customers'] },
  { tabId: 'tab-suppliers', label: 'الموردين', aliases: ['الموردين', 'الموردون', 'suppliers'] },
  { tabId: 'tab-sales-invoice', label: 'فاتورة البيع', aliases: ['فاتوره البيع', 'فاتورة البيع', 'المبيعات', 'فواتير البيع', 'sales invoice'] },
  { tabId: 'tab-purchase-invoice', label: 'فاتورة الشراء', aliases: ['فاتوره الشراء', 'فاتورة الشراء', 'المشتريات', 'فواتير الشراء', 'purchase invoice'] },
  { tabId: 'tab-orders', label: 'الأوردرات', aliases: ['الاوردرات', 'الأوردرات', 'الطلبات', 'orders'] },
  { tabId: 'tab-receipt', label: 'سند القبض', aliases: ['سند قبض', 'القبض', 'receipt'] },
  { tabId: 'tab-voucher', label: 'سند الصرف', aliases: ['سند صرف', 'الصرف', 'voucher'] },
  { tabId: 'tab-journal', label: 'قيد اليومية', aliases: ['قيد يوميه', 'قيد اليومية', 'القيود', 'journal'] },
  { tabId: 'tab-movement', label: 'الحركة', aliases: ['الحركه', 'الحركة', 'movement'] },
  { tabId: 'tab-sales-purchase-movement', label: 'حركة المبيعات والمشتريات', aliases: ['حركة المبيعات', 'حركة المشتريات', 'حركه المبيعات والمشتريات'] },
  { tabId: 'tab-reports', label: 'التقارير', aliases: ['التقارير', 'كشف حساب', 'الكشوفات', 'reports'] },
  { tabId: 'tab-quick-statement', label: 'كشف الحساب السريع', aliases: ['كشف حساب سريع', 'الكشف السريع', 'quick statement'] },
  { tabId: 'tab-category-report', label: 'تقرير الأصناف', aliases: ['تقرير الاصناف', 'تقرير حسب الاصناف', 'category report'] },
  { tabId: 'tab-tax-report', label: 'تقرير الضرائب', aliases: ['تقرير الضرائب', 'الضرائب', 'tax report'] },
  { tabId: 'tab-tax-declaration', label: 'الإقرار الضريبي', aliases: ['الاقرار الضريبي', 'الإقرار الضريبي', 'tax declaration'] },
  { tabId: 'tab-trial-balance', label: 'ميزان المراجعة', aliases: ['ميزان المراجعه', 'ميزان المراجعة', 'trial balance'] },
  { tabId: 'tab-income-statement', label: 'قائمة الدخل', aliases: ['قائمه الدخل', 'قائمة الدخل', 'income statement'] },
  { tabId: 'tab-balance-sheet', label: 'الميزانية العمومية', aliases: ['الميزانيه العموميه', 'الميزانية العمومية', 'balance sheet'] },
  { tabId: 'tab-general-ledger', label: 'دفتر الأستاذ', aliases: ['دفتر الاستاذ', 'دفتر الأستاذ', 'general ledger'] },
  { tabId: 'tab-opening', label: 'الأرصدة الافتتاحية', aliases: ['الارصده الافتتاحيه', 'الأرصدة الافتتاحية', 'opening'] },
  { tabId: 'tab-gold-items', label: 'أصناف العيارات', aliases: ['اصناف العيارات', 'أصناف العيارات', 'الاصناف', 'gold items'] },
  { tabId: 'tab-branches', label: 'الفروع', aliases: ['الفروع', 'الفرع', 'إدارة الفروع', 'ادارة الفروع', 'branches', 'branch'] },
  { tabId: 'tab-users', label: 'المستخدمين', aliases: ['المستخدمين', 'users'] },
  { tabId: 'tab-open-positions', label: 'المراكز المفتوحة', aliases: ['المراكز المفتوحه', 'المراكز المفتوحة', 'open positions'] },
  { tabId: 'tab-company-settings', label: 'إعدادات الشركة', aliases: ['اعدادات الشركه', 'إعدادات الشركة', 'الاعدادات', 'settings'] },
  { tabId: 'tab-cloud-settings', label: 'إعدادات السحابة', aliases: ['اعدادات السحابه', 'إعدادات السحابة', 'السحابه', 'cloud settings'] },
];

const screenFolderByTabId = {
  'tab-dashboard': 'dashboard',
  'tab-accounts': 'accounts',
  'tab-customers': 'customers',
  'tab-suppliers': 'suppliers',
  'tab-voucher': 'voucher',
  'tab-receipt': 'receipt',
  'tab-sales-invoice': 'sales-invoice',
  'tab-purchase-invoice': 'purchase-invoice',
  'tab-orders': 'orders',
  'tab-sales-purchase-movement': 'sales-purchase-movement',
  'tab-movement': 'movement',
  'tab-reports': 'reports',
  'tab-quick-statement': 'quick-statement',
  'tab-category-report': 'category-report',
  'tab-tax-report': 'tax-report',
  'tab-tax-declaration': 'tax-declaration',
  'tab-trial-balance': 'trial-balance',
  'tab-income-statement': 'income-statement',
  'tab-balance-sheet': 'balance-sheet',
  'tab-general-ledger': 'general-ledger',
  'tab-opening': 'opening',
  'tab-journal': 'journal',
  'tab-gold-items': 'gold-items',
  'tab-branches': 'branches',
  'tab-users': 'users',
  'tab-open-positions': 'open-positions',
  'tab-company-settings': 'company-settings',
  'tab-cloud-settings': 'cloud-settings',
};

module.exports = {
  screenCatalog,
  screenFolderByTabId,
};
